### ISSUE TITLE
chrome and compose

### ISSUE THREAD

**Issue by rain1024** [jfrazelle/dockerfiles#169]
I ran  chrome successfully in docker with this shell

```
xhost +
export DATA_HOME="/home/test/chrome"
docker run -it --net host --cpuset-cpus 0 \
-e DISPLAY=unix$DISPLAY \
-v /tmp/.X11-unix:/tmp/.X11-unix \
-v $DATA_HOME/data/Downloads:/root/Downloads \
-v $DATA_HOME/data:/data \
-v /deb/shm:/dev/shm \
--device /dev/snd \
chrome --user-data-dir=/data www.google.com
```

My Environment

- ubuntu 14.04
- docker 1.11

Today, I want to run multiples chrome, so I think about **docker-compose**

I wrote `docker-compose.yml` file

```
version: "2"
services:
  browser:
    image: chrome
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /deb/shm:/dev/shm
      - ./data:/data
      - ./data/Downloads:/root/Downloads
    network_mode: host
    cpuset: "0"
    devices:
      - "/dev/snd"
```

Then, I run it with this command

```
docker-compose up
```

But it doesn't work, here are the logs

```
Starting dist_browser_1
Attaching to dist_browser_1
browser_1  | [1:1:0727/070304:ERROR:browser_main_loop.cc(271)] Gtk: cannot open display: 
dist_browser_1 exited with code 1
```

My questions

1. Is it possible to run chrome with docker-compose? I think it didn't work because I miss `xhost +` and `-it` switch
2. How can I add `xhost +` and `-it` and `chrome arguments` (like --user-data-dir=/data www.google.com) with docker-compose

Thank you so much

**Updated**

Here is my final solution in `docker-compose.yml` file

```
version: "2"
services:
  browser_0:
    image: chrome
    command: --user-data-dir=/data www.facebook.com
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /deb/shm:/dev/shm
      - ./0/data:/data
      - ./0/data/Downloads:/root/Downloads
    network_mode: host
    cpuset: "0"
    devices:
      - "/dev/snd"
    environment:
      - DISPLAY=unix:0
  browser_1:
    image: chrome
    command: --user-data-dir=/data www.google.com
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /deb/shm:/dev/shm
      - ./1/data:/data
      - ./1/data/Downloads:/root/Downloads
    network_mode: host
    cpuset: "0"
    devices:
      - "/dev/snd"
    environment:
      - DISPLAY=unix:0
```

**Comment by koep** [comment]
You forgot to add the $DISPLAY variable to docker-compose.

**Comment by rain1024** [comment]
yes, thanks koep.

I did it, I add

```
environment:
  - DISPLAY=unix:0
```

now I can run multiple chrome image with docker-compose

@koep, have you any idea about add chrome arguments into compose?

**Comment by koep** [comment]
No I don't - maybe check the docker-compose refernce/docs?

**Comment by rain1024** [comment]
I'm trying to override default command with `command` option

**Comment by rain1024** [comment]
finally, I solved this problem

I use `command` in `docker-compose` to add arguments to chrome

Here is my final `docker-compose.yml` file

```
version: "2"
services:
  browser_0:
    image: chrome
    command: --user-data-dir=/data www.facebook.com
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /deb/shm:/dev/shm
      - ./0/data:/data
      - ./0/data/Downloads:/root/Downloads
    network_mode: host
    cpuset: "0"
    devices:
      - "/dev/snd"
    environment:
      - DISPLAY=unix:0
  browser_1:
    image: chrome
    command: --user-data-dir=/data www.google.com
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /deb/shm:/dev/shm
      - ./1/data:/data
      - ./1/data/Downloads:/root/Downloads
    network_mode: host
    cpuset: "0"
    devices:
      - "/dev/snd"
    environment:
      - DISPLAY=unix:0
```
